    Write a function so that the columns of the output matrix are powers of the input
    vector.
    The order of the powers is determined by the increasing boolean argument. Specifically, when
    increasing is False, the i-th output column is the input vector raised element-wise to the power
    of N - i - 1.

    HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
    Theophile Vandermonde.

In [8]:
import numpy as np
def alex_theo_vander(input_v, N, increasing=False):
    if not increasing:
        output_m = np.array([x**(N-1-i) for x in input_v for i in range(N)]).reshape(input_v.size,N)
    elif increasing:
        output_m = np.array([x**i for x in input_v for i in range(N)]).reshape(input_v.size,N)
    
    return output_m

In [9]:
alex_theo_vander(np.array([1,2,3,4,5]),3)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1],
       [25,  5,  1]])

In [11]:
alex_theo_vander(np.array([1,2,3,4,5]),3,False)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1],
       [25,  5,  1]])

In [10]:
alex_theo_vander(np.array([1,2,3,4,5]),3,True)

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  4, 16],
       [ 1,  5, 25]])

    Problem Statement 2:
    Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
    the given sequence is defined as follows:
    The moving average sequence has n-k+1 elements as shown below.
    The moving averages with k=4 of a ten-value sequence (n=10) is shown below
    i 1 2 3 4 5 6 7 8 9 10
    ===== == == == == == == == == == ==
    Input 10 20 30 40 50 60 70 80 90 100
    y1 25 = (10+20+30+40)/4
    y2 35 = (20+30+40+50)/4
    y3 45 = (30+40+50+60)/4
    y4 55 = (40+50+60+70)/4
    y5 65 = (50+60+70+80)/4
    y6 75 = (60+70+80+90)/4
    y7 85 = (70+80+90+100)/4
    Thus, the moving average sequence has n-k+1=10-4+1=7 values.
    Question: Write a function to find moving average in an array over a window:
    Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [44]:
def mv_avg(g_seq,window):
    return [ round(sum(g_seq[i:i+window])/window,2) for i in range(0,len(g_seq),window-(window-1)) if len(g_seq[i:i+window])==window]

In [45]:
mv_avg([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150],3)

[5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]

In [47]:
mv_avg([10,20,30,40,50,60,70,80,90,100],4)

[25.0, 35.0, 45.0, 55.0, 65.0, 75.0, 85.0]